//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.general {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class aspx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal aspx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.general.aspx", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BodyItems {
            get {
                return ResourceManager.GetString("BodyItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعمال.
        /// </summary>
        internal static string business {
            get {
                return ResourceManager.GetString("business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عربى.
        /// </summary>
        internal static string ddlLangAr {
            get {
                return ResourceManager.GetString("ddlLangAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انجليزي.
        /// </summary>
        internal static string ddlLangEn {
            get {
                return ResourceManager.GetString("ddlLangEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من نحن.
        /// </summary>
        internal static string lblAboutUs {
            get {
                return ResourceManager.GetString("lblAboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمات منفذة.
        /// </summary>
        internal static string lblAccessServices {
            get {
                return ResourceManager.GetString("lblAccessServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعمال.
        /// </summary>
        internal static string lblBusiness {
            get {
                return ResourceManager.GetString("lblBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمات ملغاة.
        /// </summary>
        internal static string lblCanceledServices {
            get {
                return ResourceManager.GetString("lblCanceledServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نموذج تخليص جمركي.
        /// </summary>
        internal static string lblClearanceForm {
            get {
                return ResourceManager.GetString("lblClearanceForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمة العملاء.
        /// </summary>
        internal static string lblCustomerServices {
            get {
                return ResourceManager.GetString("lblCustomerServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نماذج التخليص الجمركي.
        /// </summary>
        internal static string lblCustomsClearance {
            get {
                return ResourceManager.GetString("lblCustomsClearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسئلة متكررة.
        /// </summary>
        internal static string lblFaq {
            get {
                return ResourceManager.GetString("lblFaq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كن منفذا.
        /// </summary>
        internal static string lblFunctions {
            get {
                return ResourceManager.GetString("lblFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت الموافقة.
        /// </summary>
        internal static string lblHasBeenApproved {
            get {
                return ResourceManager.GetString("lblHasBeenApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نماذج وزارة الصحة.
        /// </summary>
        internal static string lblHealthMinistry {
            get {
                return ResourceManager.GetString("lblHealthMinistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرسائل الواردة.
        /// </summary>
        internal static string lblIncomingMessages {
            get {
                return ResourceManager.GetString("lblIncomingMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نماذج مكتب العمل.
        /// </summary>
        internal static string lblLabourOffice {
            get {
                return ResourceManager.GetString("lblLabourOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نماذج وزاره التجارة.
        /// </summary>
        internal static string lblMinistryCommerce {
            get {
                return ResourceManager.GetString("lblMinistryCommerce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وظائف.
        /// </summary>
        internal static string lblOutlet {
            get {
                return ResourceManager.GetString("lblOutlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الدفع والتأكيد.
        /// </summary>
        internal static string lblPaymentConfirmation {
            get {
                return ResourceManager.GetString("lblPaymentConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طرق الدفع.
        /// </summary>
        internal static string lblPaymentMethods {
            get {
                return ResourceManager.GetString("lblPaymentMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانتظار الموافقة.
        /// </summary>
        internal static string lblPendingApprovals {
            get {
                return ResourceManager.GetString("lblPendingApprovals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أفراد.
        /// </summary>
        internal static string lblPersonal {
            get {
                return ResourceManager.GetString("lblPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمات مرفوضة.
        /// </summary>
        internal static string lblRejectedServices {
            get {
                return ResourceManager.GetString("lblRejectedServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شركة القنصل الرقمي المالكة لبوابة خدمات كوم .
        /// </summary>
        internal static string lblRightsReserved {
            get {
                return ResourceManager.GetString("lblRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خصوصية خدمات كوم.
        /// </summary>
        internal static string lblServicePrivacy {
            get {
                return ResourceManager.GetString("lblServicePrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمات.
        /// </summary>
        internal static string lblServices {
            get {
                return ResourceManager.GetString("lblServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات الشحن.
        /// </summary>
        internal static string lblShippingInformation {
            get {
                return ResourceManager.GetString("lblShippingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نماذج تهمك.
        /// </summary>
        internal static string lblSimilarModels {
            get {
                return ResourceManager.GetString("lblSimilarModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يكتب هنا رابط فرعى.
        /// </summary>
        internal static string lblSubLink {
            get {
                return ResourceManager.GetString("lblSubLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمات كوم.
        /// </summary>
        internal static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتفاقية الاستخدام.
        /// </summary>
        internal static string lblUseAgreement {
            get {
                return ResourceManager.GetString("lblUseAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دليل الاستخدام.
        /// </summary>
        internal static string lblUsersManual {
            get {
                return ResourceManager.GetString("lblUsersManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LeftMenu {
            get {
                return ResourceManager.GetString("LeftMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LowerMenu {
            get {
                return ResourceManager.GetString("LowerMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أفراد.
        /// </summary>
        internal static string personal {
            get {
                return ResourceManager.GetString("personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RightMenu {
            get {
                return ResourceManager.GetString("RightMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اكتب نص البحث هنا .......
        /// </summary>
        internal static string txtSearcBox {
            get {
                return ResourceManager.GetString("txtSearcBox", resourceCulture);
            }
        }
    }
}
